language: java

sudo: required

services:
    - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install sed
  - sed -i "s/USERNAME/$GITHUB_USER/g" vagrant/template/settings.xml.template
  - sed -i "s/TOKEN/$GITHUB_PWD/g" vagrant/template/settings.xml.template
  - cp vagrant/template/settings.xml.template vagrant/template/settings.xml
  - cp vagrant/template/settings.xml.template ~/.m2/settings.xml
stages:
  - build
  - name: docker-tag
    if: (tag IS present) AND (branch = master) AND (type != pull_request)
  - name: docker-push
    if: (branch = master) AND (type != pull_request)

jobs:
    include:
        - stage: build
          name: war
          script: mvn --batch-mode --define java.net.useSystemProxies=true package
          before_deploy: cp target/plantuml.war target/plantuml-${TRAVIS_BRANCH}.war
          deploy:
              provider: releases
              api_key: "$GITHUB_TOKEN"
              file: "target/plantuml-${TRAVIS_BRANCH}.war"
              skip_cleanup: true
              on:
                  tags: true

        - stage: docker-tag
          name: jetty
          script:
              - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
              - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              - docker build --pull -t jgraph/plantuml-server:jetty-$TRAVIS_TAG -f Dockerfile.jetty .
              - docker push jgraph/plantuml-server:jetty-$TRAVIS_TAG
          on:
              tags: true

        - stage: docker-tag
          name: tomcat
          script:
              - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
              - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              - docker build --pull -t jgraph/plantuml-server:tomcat-$TRAVIS_TAG -f Dockerfile.tomcat .
              - docker push jgraph/plantuml-server:tomcat-$TRAVIS_TAG
          on:
              tags: true

        - stage: docker-push
          name: jetty
          script:
              - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              - docker build --pull -t jgraph/plantuml-server:jetty -f Dockerfile.jetty .
              - docker tag jgraph/plantuml-server:jetty jgraph/plantuml-server:latest
              - docker push jgraph/plantuml-server:jetty
              - docker push jgraph/plantuml-server:latest
        - stage: docker-push
          name: tomcat
          script:
              - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              - docker build --pull -t jgraph/plantuml-server:tomcat -f Dockerfile.tomcat .
              - docker push jgraph/plantuml-server:tomcat
